# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Hindustan Jades Project'
description:      'Hindustan Jades Project Website with Jekyll'
url:              'https://Project-Kleutghen.github.io'
baseurl:          '/jades-project-9'
copyright:        'Dr. Kristina Kleutghen, 2023'
logo:             '/assets/logo.jpg'
default_thumb:    '/assets/default.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibit: 
    output: true
  jades: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'hindustan_item' # the layout for the pages to use
    metadata:
      source: 'jades_meta.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/jades' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      jades:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - object_origin
          - cultural_context
          - label_en
          - label_zh
          - _date
          - object_type_en
          - object_type_zh
          - _collection
          - inscription_text_zh
          - inscription_text_en
          - pub_text
          - pub_text_source
# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'About'
        link: '/about/'
      - label: 'Documentation'
        link: 'https://minicomp.github.io/wiki/wax/'
      - label: 'Credits'
        link: '/credits/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'
  - label: 'Maps'
    sub:
      - label: 'Forbidden City Map'
        link: '/forbiddencity/'
      - label: 'Published Place Names'
        link: '/publishedplace/'
      - label: 'Incised Place Names'
        link: '/incisedplace/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/Project-Kleutghen/jades-project-9'
    - label: 'Credits'
      link: '/credits'
  logos:
    - name: 'Jades Logo'
      img: '/img/logo.jpg'
    - name: 'WashU Logo'
      img: '/img/WashULogoRGBLong.png'


# FIN
